version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - enhancement
    groups:
      web-dev:
        patterns:
          - "@types/*"
          - eslint*
          - typescript

  - package-ecosystem: pip
    directory: /services/math
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - enhancement

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - enhancement
